const express=require('express');const path=require('path');const dotenv=require('dotenv');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');const {MongoClient,ObjectId}=require('mongodb');
dotenv.config();const app=express();const PORT=process.env.PORT||5000;const uri=process.env.MONGODB_URI;
if(!uri||!process.env.JWT_SECRET){console.error('ERROR: MONGODB_URI and JWT_SECRET are required in .env');process.exit(1)}
const client=new MongoClient(uri);let users,products,orders;app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
function token(u){return jwt.sign({userId:u._id.toString(),role:u.role},process.env.JWT_SECRET,{expiresIn:'7d'})}
function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({message:'Please login first'});try{const d=jwt.verify(h.slice(7),process.env.JWT_SECRET);req.userId=new ObjectId(d.userId);req.role=d.role;next()}catch{return res.status(401).json({message:'Invalid or expired login'})}}
function admin(req,res,next){if(req.role!=='admin')return res.status(403).json({message:'Admin access required'});next()}
const productOut=p=>({...p,_id:p._id.toString(),price:Number(p.price),stock:Number(p.stock||0)});
async function seed(){if(await products.countDocuments()===0)await products.insertMany([
{name:'Wireless Headphones',description:'Comfortable wireless headphones with deep bass and clear sound.',price:1499,category:'Electronics',image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',stock:25,createdAt:new Date()},
{name:'Smart Watch',description:'Stylish smart watch for fitness tracking and daily notifications.',price:2199,category:'Electronics',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',stock:18,createdAt:new Date()},
{name:'Running Shoes',description:'Lightweight running shoes designed for everyday workouts.',price:1799,category:'Fashion',image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',stock:30,createdAt:new Date()},
{name:'Backpack',description:'Durable everyday backpack with laptop compartment.',price:999,category:'Fashion',image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',stock:40,createdAt:new Date()},
{name:'Coffee Mug',description:'Minimal ceramic mug for home, college, or office.',price:349,category:'Home',image:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=800&q=80',stock:50,createdAt:new Date()},
{name:'Desk Lamp',description:'Modern LED desk lamp with a clean study-friendly design.',price:799,category:'Home',image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',stock:22,createdAt:new Date()}]);
const email=(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),pw=process.env.ADMIN_PASSWORD||'';if(email&&pw&&!await users.findOne({email})){await users.insertOne({name:'Store Admin',email,password:await bcrypt.hash(pw,10),role:'admin',createdAt:new Date()});console.log('Demo admin created:',email)}}
app.post('/api/register',async(req,res)=>{try{const name=String(req.body.name||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!name||!email||!password)return res.status(400).json({message:'All fields are required'});if(password.length<6)return res.status(400).json({message:'Password must be at least 6 characters'});if(await users.findOne({email}))return res.status(409).json({message:'Email already registered'});const u={name,email,password:await bcrypt.hash(password,10),role:'user',createdAt:new Date()};const r=await users.insertOne(u);u._id=r.insertedId;res.status(201).json({token:token(u),user:{id:u._id.toString(),name:u.name,email:u.email,role:u.role}})}catch(e){console.error(e);res.status(500).json({message:'Registration failed'})}});
app.post('/api/login',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),u=await users.findOne({email});if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({message:'Invalid email or password'});res.json({token:token(u),user:{id:u._id.toString(),name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({message:'Login failed'})}});
app.get('/api/products',async(req,res)=>{try{const q=String(req.query.q||'').trim(),cat=String(req.query.category||'').trim(),f={};if(cat&&cat!=='All')f.category=cat;if(q)f.$or=[{name:{$regex:q,$options:'i'}},{description:{$regex:q,$options:'i'}}];res.json((await products.find(f).sort({createdAt:-1}).toArray()).map(productOut))}catch(e){res.status(500).json({message:'Could not load products'})}});
app.post('/api/orders',auth,async(req,res)=>{try{const items=Array.isArray(req.body.items)?req.body.items:[],c=req.body.customer||{};if(!items.length)return res.status(400).json({message:'Cart is empty'});if(!c.name||!c.phone||!c.address)return res.status(400).json({message:'Name, phone and address are required'});let total=0,oi=[];for(const x of items){if(!ObjectId.isValid(x.productId))return res.status(400).json({message:'Invalid product'});const p=await products.findOne({_id:new ObjectId(x.productId)}),qty=Math.max(1,Number(x.quantity||1));if(!p)return res.status(404).json({message:'Product not found'});if(p.stock<qty)return res.status(400).json({message:`${p.name} has only ${p.stock} left`});oi.push({productId:p._id,name:p.name,price:Number(p.price),quantity:qty,image:p.image});total+=Number(p.price)*qty;await products.updateOne({_id:p._id},{$inc:{stock:-qty}})}const o={userId:req.userId,items:oi,total,customer:{name:String(c.name).trim(),phone:String(c.phone).trim(),address:String(c.address).trim()},status:'Placed',createdAt:new Date()},r=await orders.insertOne(o);res.status(201).json({message:'Order placed successfully',orderId:r.insertedId.toString(),total})}catch(e){console.error(e);res.status(500).json({message:'Could not place order'})}});
app.get('/api/orders/my',auth,async(req,res)=>{const a=await orders.find({userId:req.userId}).sort({createdAt:-1}).toArray();res.json(a.map(o=>({...o,_id:o._id.toString()})))})
app.get('/api/admin/products',auth,admin,async(req,res)=>res.json((await products.find().sort({createdAt:-1}).toArray()).map(productOut)));
app.post('/api/admin/products',auth,admin,async(req,res)=>{try{const p={name:String(req.body.name||'').trim(),description:String(req.body.description||'').trim(),price:Number(req.body.price),category:String(req.body.category||'Other').trim(),image:String(req.body.image||'https://via.placeholder.com/800x600?text=Product'),stock:Math.max(0,Number(req.body.stock||0)),createdAt:new Date()};if(!p.name||!p.description||!Number.isFinite(p.price))return res.status(400).json({message:'Name, description and valid price are required'});const r=await products.insertOne(p);p._id=r.insertedId;res.status(201).json(productOut(p))}catch(e){res.status(500).json({message:'Could not add product'})}});
app.put('/api/admin/products/:id',auth,admin,async(req,res)=>{try{const u={};['name','description','category','image'].forEach(k=>{if(req.body[k]!==undefined)u[k]=String(req.body[k]).trim()});if(req.body.price!==undefined)u.price=Number(req.body.price);if(req.body.stock!==undefined)u.stock=Math.max(0,Number(req.body.stock));const r=await products.findOneAndUpdate({_id:new ObjectId(req.params.id)},{$set:u},{returnDocument:'after'});if(!r)return res.status(404).json({message:'Product not found'});res.json(productOut(r))}catch{res.status(400).json({message:'Invalid product id'})}});
app.delete('/api/admin/products/:id',auth,admin,async(req,res)=>{try{const r=await products.deleteOne({_id:new ObjectId(req.params.id)});if(!r.deletedCount)return res.status(404).json({message:'Product not found'});res.json({message:'Product deleted'})}catch{res.status(400).json({message:'Invalid product id'})}});
app.get('/api/admin/orders',auth,admin,async(req,res)=>{const a=await orders.aggregate([{$lookup:{from:'users',localField:'userId',foreignField:'_id',as:'user'}},{$unwind:{path:'$user',preserveNullAndEmptyArrays:true}},{$sort:{createdAt:-1}}]).toArray();res.json(a.map(o=>({...o,_id:o._id.toString(),user:o.user?{name:o.user.name,email:o.user.email}:null})))})
app.put('/api/admin/orders/:id',auth,admin,async(req,res)=>{try{const allowed=['Placed','Processing','Shipped','Delivered','Cancelled'],status=String(req.body.status||'');if(!allowed.includes(status))return res.status(400).json({message:'Invalid status'});const r=await orders.findOneAndUpdate({_id:new ObjectId(req.params.id)},{$set:{status}},{returnDocument:'after'});if(!r)return res.status(404).json({message:'Order not found'});res.json({message:'Order status updated',status})}catch{res.status(400).json({message:'Invalid order id'})}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
async function start(){try{await client.connect();const db=client.db('thiranex_ecommerce');users=db.collection('users');products=db.collection('products');orders=db.collection('orders');await users.createIndex({email:1},{unique:true});await seed();app.listen(PORT,()=>console.log(`E-Commerce website running at http://localhost:${PORT}`))}catch(e){console.error('MongoDB connection failed:',e.message);process.exit(1)}}start();
